version: '3.7'

services:
  flask-app:
    build: ./pyhon_project
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=admin
      - DB_USER=jyoti
      - DB_PASSWORD_FILE=/run/secrets/db_root_password
    secrets:
      - db_root_password

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: jyoti
      POSTGRES_PASSWORD_FILE: /run/secrets/db_root_password
    secrets:
      - db_root_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: j.jyotiranjan29@gmail.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pg_password
    secrets:
      - pg_password

secrets:
   pg_password:
     file: pg_password.txt
   db_root_password:
     file: db_root_password.txt

volumes:
  pgdata:
